lidarTopic: "/velodyne16/velodyne_points"
odomTopic: "/smart_smoother/odom_imu"
#odomTopic: /vins_estimator/imu_propagate
lineSegNum: 6
maxEdgeNum: 20
maxSurfNum: 80
edgeThreshold: 0.2
scanPeriod: 0.1




